spring:
  profiles:
    active: default
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
  properties:
    hibernate:
      format_sql: true


server:
  port: 8080
  servlet:
    context-path: /api
